// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDMLgPkrJ-pUj8jGjq_hiWXCli9OJ9p8',
    appId: '1:643578428320:web:38393d74c9f9e93de6c2c5',
    messagingSenderId: '643578428320',
    projectId: 'swift-impulse-400708',
    authDomain: 'swift-impulse-400708.firebaseapp.com',
    databaseURL: 'https://swift-impulse-400708-default-rtdb.firebaseio.com',
    storageBucket: 'swift-impulse-400708.firebasestorage.app',
    measurementId: 'G-V4YPXK6T8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLEIRhWNyaMWINjZ6Gvp2Flyv_NMsED8',
    appId: '1:643578428320:android:3de41f9cad85f55ee6c2c5',
    messagingSenderId: '643578428320',
    projectId: 'swift-impulse-400708',
    databaseURL: 'https://swift-impulse-400708-default-rtdb.firebaseio.com',
    storageBucket: 'swift-impulse-400708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAru0pX11lCNrypaS6T8R8S-3rfUHnQqp8',
    appId: '1:643578428320:ios:0c8922961f09e067e6c2c5',
    messagingSenderId: '643578428320',
    projectId: 'swift-impulse-400708',
    databaseURL: 'https://swift-impulse-400708-default-rtdb.firebaseio.com',
    storageBucket: 'swift-impulse-400708.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAru0pX11lCNrypaS6T8R8S-3rfUHnQqp8',
    appId: '1:643578428320:ios:0c8922961f09e067e6c2c5',
    messagingSenderId: '643578428320',
    projectId: 'swift-impulse-400708',
    databaseURL: 'https://swift-impulse-400708-default-rtdb.firebaseio.com',
    storageBucket: 'swift-impulse-400708.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuDMLgPkrJ-pUj8jGjq_hiWXCli9OJ9p8',
    appId: '1:643578428320:web:b008cc8557b7fdc5e6c2c5',
    messagingSenderId: '643578428320',
    projectId: 'swift-impulse-400708',
    authDomain: 'swift-impulse-400708.firebaseapp.com',
    databaseURL: 'https://swift-impulse-400708-default-rtdb.firebaseio.com',
    storageBucket: 'swift-impulse-400708.firebasestorage.app',
    measurementId: 'G-JRWVSPB4B0',
  );
}
